apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-cm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
    matchExpressions:
      - {key: tier, operator: In, values: [frontend, backend, db]}
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        tier: db
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: test-vol
              mountPath: '/etc/test-config/'
              readOnly: true
      volumes:
        - name: test-vol
          configMap:
            name: game-config