apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: nginx-app
      db: sql-db
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
        db: sql-db
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.19.10
          ports:
            - containerPort: 80
