apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-job
spec:
  template:
    metadata:
      name: countdown-job-pod
    spec:
      containers:
        - name: countdown-job-container
          image: centos:7
          command:
            - "bin/bash"
            - "-c"
            - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $ i ; done"
      restartPolicy: Never
