apiVersion: v1
kind: Pod
metadata:
  name: redis-pod-env
spec:
  containers:
    - name: redi-container-env
      image: redis
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: newsecret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: newsecret
              key: password