apiVersion: apps/v1
kind: Deployment 
metadata:
  name: redis-slave-deploy
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  template:
    metadata:
      name: redis-slave-pod
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
        - name: redis-slave-container
          image: gcr.io/google-samples/gb-redisslave:v1
          ports:
            - containerPort: 6379