apiVersion: apps/v1
kind: Deployment 
metadata:
  name: redis-master-deploy
  labels:
    app: redis
    role: master
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  template:
    metadata:
      name: redis-master-pod
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
        - name: redis-master-container
          image: k8s.gcr.io/redis:e2e
          ports:
            - containerPort: 6379