apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
  - name: redis-container
    image: redis
    volumeMounts:
      - name: test-vol
        mountPath: '/etc/test-secret/'
        readOnly: true
  volumes:
    - name: test-vol
      secret:
        secretName: newsecret