apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
    matchExpressions:
      - { key: tier, operator: In, values: [frontend, backend, db] }
      - {key: env, operator: In, values: [dev, prod]}
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
        tier: frontend
        env: dev
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
